version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cutout-generator:latest
    ports:
      - "80:80"
    volumes:
      - .:/docker
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]